# Generated by Django 5.2.3 on 2025-07-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_data_joined_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_edited',
            field=models.DateTimeField(blank=True),
        ),
    ]
