# Generated by Django 5.2.3 on 2025-07-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_blog_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
