# Generated by Django 5.2.3 on 2025-08-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_blog_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
