# Generated by Django 5.2.3 on 2025-08-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
