# Generated by Django 5.2.3 on 2025-09-07 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('date_messaged', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date_messaged', models.DateTimeField(blank=True, null=True)),
                ('read', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=255)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
