# Generated by Django 6.0 on 2026-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_media',
            field=models.ImageField(default='', upload_to='media-picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='basic-avatar.jpg', upload_to='profile_pics'),
        ),
    ]
