# Generated by Django 6.0 on 2026-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_user_post_media_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
