# Generated by Django 6.0 on 2026-01-19 20:17

import django.db.models.deletion
import django.utils.timezone
import general.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_user_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_name', models.CharField(max_length=255)),
                ('profile_img', models.ImageField(default='default.jpg', upload_to=general.models.unique_image_name)),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
